postgres:
  container_name: sandbox-db
  ports:
    - "35432:5432"
  image: postgres
  environment:
    POSTGRES_DB: "sandbox"
    POSTGRES_USER: "sandbox"
    POSTGRES_PASSWORD: "sandboxpwd"
  restart: on-failure:3